import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../services/api.js";
import { useDemoUser } from "../context/useDemoUser.js";

const Booking = () => {
  const { gigId } = useParams(); const { currentUser } = useDemoUser();
  const [gig, setGig] = useState(null); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ requirements: "", preferredDeliveryDate: "", additionalNotes: "" });
  useEffect(() => { api.get(`/gigs/${gigId}`).then((response) => setGig(response.data.data)).catch(() => setError("This gig could not be found.")); }, [gigId]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await api.post("/bookings", { gigId, clientName: currentUser.name, clientEmail: currentUser.email, ...form }); setDone(true); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to send booking request."); } finally { setSaving(false); } };
  if (done) return <div className="mx-auto max-w-xl px-6 py-24 text-center"><div className="text-5xl">🎉</div><h1 className="mt-5 text-3xl font-bold">Booking request sent</h1><p className="mt-3 leading-7 text-gray-600">{gig?.creatorName || "The creator"} will review your project brief. You can track the request in My Bookings.</p><div className="mt-8 flex justify-center gap-3"><Link to="/my-bookings" className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">View my bookings</Link><Link to="/marketplace" className="rounded-xl border border-gray-200 px-5 py-3 font-semibold">Keep exploring</Link></div></div>;
  return <div className="bg-gray-50 py-12"><div className="mx-auto grid max-w-5xl gap-8 px-6 lg:grid-cols-[1fr_0.6fr]"><form onSubmit={submit} className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Booking request</p><h1 className="mt-2 text-3xl font-bold">Tell the creator about your project.</h1><p className="mt-3 text-sm text-gray-600">Booking as {currentUser.name} ({currentUser.email})</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<label className="mt-7 grid gap-2 text-sm font-medium">Project requirements<textarea value={form.requirements} onChange={(event) => setForm({ ...form, requirements: event.target.value })} required minLength="10" rows="7" placeholder="What do you need? Include scope, goals, required features and references." className="rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-indigo-500" /></label><label className="mt-5 grid gap-2 text-sm font-medium">Preferred delivery date<input type="date" value={form.preferredDeliveryDate} onChange={(event) => setForm({ ...form, preferredDeliveryDate: event.target.value })} required min={new Date().toISOString().slice(0, 10)} className="rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-indigo-500" /></label><label className="mt-5 grid gap-2 text-sm font-medium">Additional notes <span className="font-normal text-gray-400">(optional)</span><textarea value={form.additionalNotes} onChange={(event) => setForm({ ...form, additionalNotes: event.target.value })} rows="3" className="rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-indigo-500" /></label><button disabled={saving} className="mt-8 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-60">{saving ? "Sending request…" : "Send booking request"}</button></form><aside className="h-fit rounded-3xl border border-gray-200 bg-white p-6"><p className="text-sm text-gray-500">You’re booking</p><h2 className="mt-2 text-xl font-bold">{gig?.title || "Loading…"}</h2><p className="mt-2 text-gray-600">by {gig?.creatorName}</p><div className="my-5 border-t" /><p className="text-2xl font-bold">{gig ? `₹${Number(gig.price).toLocaleString("en-IN")}` : ""}</p><p className="mt-1 text-sm text-gray-500">{gig?.deliveryDays} day delivery</p></aside></div></div>;
};
export default Booking;
