import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Sparkles } from "lucide-react";
import api from "../services/api.js";
import { useDemoUser } from "../context/useDemoUser.js";
import { Status } from "./CreatorDashboard.jsx";
import GigCard from "../components/GigCard.jsx";

const MyBookings = () => {
  const { currentUser } = useDemoUser(); const [bookings, setBookings] = useState([]); const [error, setError] = useState(""); const [recommendations, setRecommendations] = useState([]); const [recommendationSource, setRecommendationSource] = useState("");
  const load = useCallback(async () => { setError(""); setRecommendations([]); setRecommendationSource(""); try { const response = await api.get("/bookings/client", { params: { clientEmail: currentUser.email } }); const data = response.data.data; setBookings(data); const declined = data.find((booking) => booking.status === "DECLINED" && booking.gigId?.category); if (declined) { const recommendationResponse = await api.post("/ai/recommendations", { bookingId: declined._id }); setRecommendations(recommendationResponse.data.data); setRecommendationSource(recommendationResponse.data.meta.source); } } catch { setError("Unable to load your bookings. Please make sure the backend is running."); } }, [currentUser.email]);
  // oxlint-disable-next-line react/set-state-in-effect -- The asynchronous API request owns these post-response state updates.
  useEffect(() => { load(); }, [load]);
  return <div className="bg-gray-50 py-10"><div className="mx-auto max-w-7xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Client workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight">My bookings</h1><p className="mt-2 text-gray-600">Tracking requests for {currentUser.name}.</p>{error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{!error && bookings.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-gray-300 bg-white p-12 text-center"><h2 className="text-xl font-bold">No bookings yet</h2><p className="mt-2 text-gray-500">Find a creator and send your first project brief.</p><Link to="/marketplace" className="mt-5 inline-block rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Explore gigs</Link></div>}<div className="mt-8 space-y-4">{bookings.map((booking) => <article key={booking._id} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{booking.gigId?.title || "Gig no longer available"}</h2><Status status={booking.status} /></div><p className="mt-2 text-sm text-gray-600">Creator: {booking.creatorName} {booking.gigId?.price && `· ₹${Number(booking.gigId.price).toLocaleString("en-IN")}`}</p><p className="mt-4 max-w-3xl text-sm leading-6 text-gray-700">{booking.requirements}</p>{booking.status === "DECLINED" && <div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800"><strong>Why it was declined:</strong> {booking.declineReason || "The creator was unable to take this request."}</div>}</div>{booking.gigId && <Link to={`/gigs/${booking.gigId._id}`} className="h-fit shrink-0 rounded-xl border border-gray-200 px-4 py-2 text-center text-sm font-semibold hover:border-indigo-300 hover:text-indigo-600">View gig</Link>}</div></article>)}</div>{recommendations.length > 0 && <section className="mt-12 rounded-3xl border border-indigo-100 bg-indigo-50/50 p-6"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-5 w-5 text-indigo-600" /><div><h2 className="text-xl font-bold">AI-picked alternatives</h2><p className="mt-1 text-sm text-gray-600">{recommendationSource === "openrouter" ? "Suggestions are based on your declined brief and comparable creator gigs." : "Similar gigs are shown while AI suggestions are unavailable."}</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{recommendations.map(({ gig, reason }) => <div key={gig._id}><GigCard gig={gig} /><p className="mt-2 px-1 text-sm text-indigo-900">Why this may fit: {reason}</p></div>)}</div></section>}</div></div>;
};
export default MyBookings;
